### ISSUE TITLE
Save failed with return code false, see debug

### ISSUE THREAD

**Issue by kstanley-contec** [domcleal/puppet-augeas-ng#1]
I am using version 0.0.1 version of puppet-augeas-ng, and when I run puppet on my remote agent I get the following error for the following definition:
## Definition

```
augeasng { 'php_conf_d':
    provider    => 'augparse',
    incl        => '/usr/local/etc/php/5.3/conf.d/ext-xcache.ini',
    lens        => '/usr/local/share/augeas/lenses/dist/php.aug',
    changes     => [
        'set "/files/usr/local/etc/php/5.3/conf.d/ext-xcache.ini/xcache/xcache.size" "1024000"',
        'set "/files/usr/local/etc/php/5.3/conf.d/ext-xcache.ini/xcache/xcache.count" "4"',
    ],
}
```

```
Debug: Augeasng[php_conf_d](provider=augparse): Opening augeas with root /, lens path , flags 64
Debug: Augeasng[php_conf_d](provider=augparse): Augeas version 1.4.0 is installed
Debug: Augeasng[php_conf_d](provider=augparse): Will attempt to save and only run if files changed
Debug: Augeasng[php_conf_d](provider=augparse): sending command 'set' with params ["/files/usr/local/etc/php/5.3/conf.d/ext-xcache.ini/xcache/xcache.size", "1024000"]
Debug: Augeasng[php_conf_d](provider=augparse): sending command 'set' with params ["/files/usr/local/etc/php/5.3/conf.d/ext-xcache.ini/xcache/xcache.count", "4"]
Debug: Augeasng[php_conf_d](provider=augparse): Closed the augeas connection
Error: /Stage[main]/Main/Node[default]/Augeasng[php_conf_d]: Could not evaluate: Save failed with return code false, see debug
```

My puppet master is running Mac OS X 10.11.4 (El Capitan), ruby 2.0.0p648, gem 2.0.14.1, with the following gems, and augtool 1.4.0 from Homebrew 0.9.9:

```
bigdecimal (1.2.0)
CFPropertyList (2.2.8)
diff-lcs (1.2.5)
hiera (3.1.1)
io-console (0.4.2)
json (1.7.7)
json_pure (1.8.3)
libxml-ruby (2.6.0)
metaclass (0.0.4)
minitest (4.3.2)
mocha (1.1.0)
nokogiri (1.5.6)
passenger (5.0.27)
psych (2.0.0)
rack (1.6.4)
rake (0.9.6)
rdoc (4.0.0)
rspec (3.4.0)
rspec-core (3.4.4)
rspec-expectations (3.4.0)
rspec-mocks (3.4.1)
rspec-support (3.4.1)
ruby-augeas (0.5.0)
sqlite3 (1.3.7)
test-unit (2.0.0.0)
```

My puppet master is running Mac OS X 10.10.3 (Yosimite), ruby 2.0.0p481, gem 2.0.14, with the following gems, and augtool 1.4.0 from Homebrew 0.9.8:

```
bigdecimal (1.2.0)
CFPropertyList (2.2.8)
io-console (0.4.2)
json (1.7.7)
libxml-ruby (2.6.0)
minitest (4.3.2)
nokogiri (1.5.6)
psych (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
ruby-augeas (0.5.0)
sqlite3 (1.3.7)
test-unit (2.0.0.0)
```

I do plan to upgrade my agent to the same OS version as the master, which would bump my ruby version on the agent. But I suspect that the fault may be on how I've configured puppet as this is my first attempt at using your module (thank you btw for having a backward compatible module for augeas). If there is anything you can see that I might be doing wrong, or if you'd like me to provide more information to troubleshoot, I'd be more than happy to assist.

**Comment by domcleal** [comment]
This module is unmaintained - it hasn't been updated for five years.  If you want to develop it, please do so, but I'm not maintaining it.  Please don't use it.

**Comment by kstanley-contec** [comment]
I almost forgot to mention that I am running the command `sudo puppet agent --test --debug` from my agent to test changes.

**Comment by kstanley-contec** [comment]
Thank you for the prompt response, and I'm sad to hear that. Since this project is not going anywhere, would you have any suggestions for comparable modules I could use in its place?

**Comment by domcleal** [comment]
Just use the built in `augeas` type and provider.  If you have improvements to make to it, submit changes to Puppet core.
